# Generated by Django 4.0.2 on 2022-02-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicgenre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='document',
            new_name='upload_music',
        ),
    ]
